name: Build and push Python app to ACR

on:
  push:
    branches: [ "main" ]

env:
  AZURE_CONTAINER_REGISTRY: "micrpython21311.azurecr.io"
  ACR_USERNAME: ${{ secrets.PYTHONRSSAPP_REGISTRY_USERNAME }}
  ACR_PASSWORD: ${{ secrets.PYTHONRSSAPP_REGISTRY_PASSWORD }}

  PROJECT_NAME: "rss_app"
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Azure Container Registry Login
      uses: azure/docker-login@v2
      with:
        login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}
        username: ${{ env.ACR_USERNAME }}
        password: ${{ env.ACR_PASSWORD }}
    
    - name: Build and push Docker image
      run: |
        docker build . -t ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.PROJECT_NAME }}:${{ env.IMAGE_TAG }}
        docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.PROJECT_NAME }}:${{ env.IMAGE_TAG }}
